name: GitOps Infra Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
